com.fasterxml.jackson.*:jackson-* = 2.16.0
com.google.guava:guava = 33.4.0-jre
org.assertj:assertj-core = 3.27.3
org.immutables:value = 2.10.1
org.junit.jupiter:junit-jupiter = 5.11.4
org.jetbrains:annotations = 26.0.1
com.github.ben-manes.caffeine:caffeine = 3.2.0
org.awaitility:awaitility = 4.2.2

# Unnecessary once we have lock files
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
