import org.jetbrains.grammarkit.tasks.GenerateParserTask
import org.jetbrains.grammarkit.tasks.GenerateLexerTask

apply plugin: 'java'
apply plugin: 'com.palantir.external-publish-intellij'
apply plugin: 'org.jetbrains.grammarkit'

intellij {
    pluginName = "gradle-consistent-versions-idea-plugin"
    updateSinceUntilBuild = true
    version = "2024.1"
    plugins = ['java', 'org.jetbrains.plugins.gradle']
}

patchPluginXml {
    sinceBuild = '241' // TODO: test against this version of IntelliJ to ensure no regressions
    untilBuild = ''
}

// Javadoc fails if there are no public classes to javadoc, so make it stop complaining.
tasks.named("javadoc", Javadoc) {
    failOnError = false
}

sourceSets.main.java.srcDirs 'build/generated/sources/intellij-parser/main/java'
sourceSets.main.java.srcDirs 'build/generated/sources/intellij-lexer/main/java'

dependencies {
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-guava'
    implementation 'com.github.ben-manes.caffeine:caffeine'
    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
}

grammarKit {
    jflexRelease = "1.9.2"
    grammarKitRelease = "2022.3.2"
}

generateParser {
    sourceFile = file('src/main/java/com/palantir/gradle/versions/props/Props.bnf')
    targetRootOutputDir = file('build/generated/sources/intellij-parser/main/java')
    pathToParser = 'com/palantir/gradle/versions/props/parser/PropsParser'
    pathToPsiRoot = 'com/palantir/gradle/versions/props/psi'
    purgeOldFiles = true
}

generateLexer {
    sourceFile = file('src/main/java/com/palantir/gradle/versions/props/Props.flex')
    targetOutputDir = file('build/generated/sources/intellij-lexer/main/java/com/palantir/gradle/versions/props')
    targetClass = 'com.palantir.gradle.versions.props.PropsLexer'
    purgeOldFiles = true
}

tasks.register('generateLockParser', GenerateParserTask) { task ->
    task.sourceFile = file('src/main/java/com/palantir/gradle/versions/lock/Lock.bnf')
    task.targetRootOutputDir = file('build/generated/sources/intellij-parser/main/java')
    task.pathToParser = 'com/palantir/gradle/versions/lock/parser/LockParser'
    task.pathToPsiRoot = 'com/palantir/gradle/versions/lock/psi'
    task.purgeOldFiles = true
}

tasks.register('generateLockLexer', GenerateLexerTask) { task ->
    task.sourceFile = file('src/main/java/com/palantir/gradle/versions/lock/Lock.flex')
    task.targetOutputDir = file('build/generated/sources/intellij-lexer/main/java/com/palantir/gradle/versions/lock')
    task.targetClass = 'com.palantir.gradle.versions.lock.LockLexer'
    task.purgeOldFiles = true
}

// Update compileJava task dependencies
tasks.named('compileJava').configure {
    dependsOn tasks.named('generateParser'), tasks.named('generateLexer'),
            tasks.named('generateLockParser'), tasks.named('generateLockLexer')
}